name: Update Submodules

permissions:
  contents: write

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout meta repo (shallow fetch with submodules)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0  # Ensure we can move branches

      - name: Update submodules to latest
        run: |
          git submodule update --remote --merge
          git add .
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git diff --cached --quiet || git commit -m "Update submodules from ${{ github.event.client_payload.repo }}"
          git push
