name: Update Submodules

permissions:
  contents: write
on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout meta repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          persist-credentials: true

      - name: Pull submodules
        run: |
          git submodule update --remote
          git add .
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit -m "Update submodules from ${{ github.event.client_payload.repo }}" || echo "No changes"
          git push
